//
// Created:		04.10.06
// Aurthor:		Iain Gilbert
// ReCreate: Artem Firstov (Konsul)

#if defined _testserver_included
#endinput
#endif

#define _testserver_included
#pragma library testserver

#include "base"

forward testserver_playerconnect(playerid);

public testserver_playerconnect(playerid)
{
//	SendPlayerScrollingText(playerid," Добро пожаловать в Grand Theft Online 0.5.9.X.X BY FP & Konsul.");
//	SendPlayerScrollingText(playerid," Этот сервер имеет некоторые изменения.");
//	SendPlayerScrollingText(playerid," Все самые последние изменения в моде GTO будут тестироваться здесь.");
//	SendPlayerScrollingText(playerid," Ошибки, крэши, торможения - это обычное дело для тестового режима.");
}
